# Makefile for building the kata file with the Google Testing Framework
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project.

# Where to find user code.
USER_DIR = .

# Flags passed to the preprocessor.
CPPFLAGS += 

# Flags passed to the C++ compiler.
CFLAGS += -g -Wall -Wextra

LD_LIBRARIES =

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.

TEXTTESTS = GildedRoseTextTests

# House-keeping build targets.

all : $(TEXTTESTS)

GildedRose.o : $(USER_DIR)/GildedRose.c

GildedRoseTextTests.o : $(USER_DIR)/GildedRoseTextTests.c

GildedRoseTextTests : GildedRoseTextTests.o GildedRose.o
	$(CC) $^ -o $@

clean :
	rm -f $(TESTS) $(TEXTTESTS) *.o *~

check-syntax:
	gcc $(CPPFLAGS) -o /dev/null -S ${CHK_SOURCES}

golden: GildedRoseTextTests
	@echo Capturing golden run
	./GildedRoseTextTests > golden.txt

test: GildedRoseTextTests
	./GildedRoseTextTests > out.txt
	@echo Comparing against golden run
	diff golden.txt out.txt
	@echo SUCCESS

kleeLlvmBitCode: GildedRose.c GildedRoseReference.c GildedRoseKleeHarness.c
	clang -I ../klee_src/include -libc=uclibc -emit-llvm -c -g -O0 -Xclang -disable-O0-optnone \
		GildedRose.c GildedRoseReference.c GildedRoseKleeHarness.c

GildedRoseCombined.bc: kleeLlvmBitCode
	llvm-link GildedRose.bc GildedRoseKleeHarness.bc GildedRoseReference.bc -o GildedRoseCombined.bc

klee: GildedRoseCombined.bc
	klee --libc=uclibc GildedRoseCombined.bc
